"""Emotion presets and preset categories for BlingSpeak."""

# Emotion presets with full parameter definitions
EMOTION_PRESETS = {
    'curious': {
        'name': 'Curious',
        'description': 'Rising questioning tone',
        'params': {
            'base_freq': 600,
            'contour': 'question',
            'contour_amount': 0.3,
            'vowel': 'o',
            'formant_shift': 1.2,
            'breathiness': 0.1,
            'brightness': 0.6,
            'attack': 0.05,
            'decay': 0.1,
            'sustain': 0.6,
            'release': 0.1,
        },
        'effects': [],
    },
    'excited': {
        'name': 'Excited',
        'description': 'Bright, energetic burst',
        'params': {
            'base_freq': 800,
            'contour': 'exclaim',
            'contour_amount': 0.4,
            'vowel': 'i',
            'formant_shift': 1.4,
            'breathiness': 0.05,
            'brightness': 0.9,
            'attack': 0.01,
            'decay': 0.08,
            'sustain': 0.5,
            'release': 0.08,
            'tremolo_rate': 8,
            'tremolo_depth': 0.15,
        },
        'effects': [],
    },
    'startled': {
        'name': 'Startled',
        'description': 'Sharp, alarmed reaction',
        'params': {
            'base_freq': 900,
            'contour': 'falling',
            'contour_amount': 0.5,
            'vowel': 'ae',
            'formant_shift': 1.5,
            'breathiness': 0.2,
            'brightness': 1.0,
            'attack': 0.005,
            'decay': 0.05,
            'sustain': 0.3,
            'release': 0.1,
        },
        'effects': [('granular', {'scatter': 0.2, 'density': 0.5})],
    },
    'happy': {
        'name': 'Happy',
        'description': 'Warm, cheerful sound',
        'params': {
            'base_freq': 650,
            'contour': 'rising',
            'contour_amount': 0.25,
            'vowel': 'i',
            'formant_shift': 1.3,
            'breathiness': 0.1,
            'brightness': 0.8,
            'attack': 0.03,
            'decay': 0.1,
            'sustain': 0.7,
            'release': 0.12,
            'vibrato_rate': 6,
            'vibrato_depth': 0.02,
        },
        'effects': [('chorus', {'rate': 2, 'depth': 0.002, 'mix': 0.2})],
    },
    'confused': {
        'name': 'Confused',
        'description': 'Wobbly, uncertain tone',
        'params': {
            'base_freq': 500,
            'contour': 'wobble',
            'contour_amount': 0.08,
            'vowel': 'uh',
            'formant_shift': 1.1,
            'breathiness': 0.15,
            'brightness': 0.5,
            'attack': 0.08,
            'decay': 0.15,
            'sustain': 0.5,
            'release': 0.15,
        },
        'effects': [],
    },
    'agreeing': {
        'name': 'Agreeing',
        'description': 'Short affirmative nod',
        'params': {
            'base_freq': 550,
            'contour': 'falling',
            'contour_amount': 0.15,
            'vowel': 'u',
            'formant_shift': 1.0,
            'breathiness': 0.05,
            'brightness': 0.6,
            'attack': 0.02,
            'decay': 0.08,
            'sustain': 0.8,
            'release': 0.1,
        },
        'effects': [],
    },
    'sad': {
        'name': 'Sad',
        'description': 'Low, falling, mournful',
        'params': {
            'base_freq': 350,
            'contour': 'falling',
            'contour_amount': 0.3,
            'vowel': 'o',
            'formant_shift': 0.9,
            'breathiness': 0.2,
            'brightness': 0.3,
            'attack': 0.1,
            'decay': 0.2,
            'sustain': 0.4,
            'release': 0.2,
        },
        'effects': [('reverb', {'decay': 0.5})],
    },
    'thinking': {
        'name': 'Thinking',
        'description': 'Contemplative, uncertain',
        'params': {
            'base_freq': 450,
            'contour': 'nervous',
            'contour_amount': 0.1,
            'vowel': 'er',
            'formant_shift': 1.0,
            'breathiness': 0.1,
            'brightness': 0.5,
            'attack': 0.06,
            'decay': 0.12,
            'sustain': 0.5,
            'release': 0.15,
        },
        'effects': [],
    },
    'delighted': {
        'name': 'Delighted',
        'description': 'Sparkling joy',
        'params': {
            'base_freq': 750,
            'contour': 'exclaim',
            'contour_amount': 0.35,
            'vowel': 'i',
            'formant_shift': 1.5,
            'breathiness': 0.05,
            'brightness': 0.95,
            'attack': 0.01,
            'decay': 0.06,
            'sustain': 0.6,
            'release': 0.1,
            'vibrato_rate': 7,
            'vibrato_depth': 0.03,
        },
        'effects': [('shimmer', {'shift_cents': 1200, 'mix': 0.15})],
    },
    'nervous': {
        'name': 'Nervous',
        'description': 'Jittery, anxious',
        'params': {
            'base_freq': 550,
            'contour': 'nervous',
            'contour_amount': 0.15,
            'vowel': 'e',
            'formant_shift': 1.2,
            'breathiness': 0.15,
            'brightness': 0.6,
            'attack': 0.02,
            'decay': 0.05,
            'sustain': 0.4,
            'release': 0.08,
            'tremolo_rate': 10,
            'tremolo_depth': 0.2,
        },
        'effects': [],
    },
    'mysterious': {
        'name': 'Mysterious',
        'description': 'Ethereal, otherworldly',
        'params': {
            'base_freq': 400,
            'contour': 'wobble',
            'contour_amount': 0.05,
            'vowel': 'u',
            'formant_shift': 0.8,
            'breathiness': 0.25,
            'brightness': 0.4,
            'attack': 0.1,
            'decay': 0.15,
            'sustain': 0.6,
            'release': 0.2,
            'vibrato_rate': 3,
            'vibrato_depth': 0.015,
        },
        'effects': [
            ('reverb', {'decay': 0.6}),
            ('shimmer', {'shift_cents': 700, 'mix': 0.1}),
        ],
    },
    'glitchy': {
        'name': 'Glitchy',
        'description': 'Digital, corrupted',
        'params': {
            'base_freq': 600,
            'contour': 'flat',
            'contour_amount': 0,
            'vowel': 'i',
            'formant_shift': 1.3,
            'breathiness': 0.0,
            'brightness': 0.8,
            'attack': 0.005,
            'decay': 0.02,
            'sustain': 0.7,
            'release': 0.02,
        },
        'effects': [
            ('bitcrush', {'bit_depth': 6, 'mix': 0.4}),
            ('ring_mod', {'carrier_freq': 150, 'mix': 0.2}),
            ('granular', {'grain_size': 0.02, 'scatter': 0.3, 'density': 1.5}),
        ],
    },
    'robotic': {
        'name': 'Robotic',
        'description': 'Mechanical, processed',
        'params': {
            'base_freq': 500,
            'contour': 'flat',
            'contour_amount': 0,
            'vowel': 'o',
            'formant_shift': 1.0,
            'breathiness': 0.0,
            'brightness': 0.7,
            'attack': 0.01,
            'decay': 0.05,
            'sustain': 0.8,
            'release': 0.05,
        },
        'effects': [
            ('ring_mod', {'carrier_freq': 80, 'mix': 0.3}),
            ('bitcrush', {'bit_depth': 10, 'mix': 0.2}),
        ],
    },
    'sparkle': {
        'name': 'Sparkle',
        'description': 'Bright, twinkling',
        'params': {
            'base_freq': 900,
            'contour': 'falling',
            'contour_amount': 0.2,
            'vowel': 'i',
            'formant_shift': 1.6,
            'breathiness': 0.1,
            'brightness': 1.0,
            'attack': 0.005,
            'decay': 0.1,
            'sustain': 0.3,
            'release': 0.15,
        },
        'effects': [
            ('shimmer', {'shift_cents': 1200, 'mix': 0.25}),
            ('reverb', {'decay': 0.4}),
        ],
    },
}

# Categories for organizing presets in UI
PRESET_CATEGORIES = {
    'Basic': ['curious', 'happy', 'sad', 'agreeing'],
    'Expressive': ['excited', 'startled', 'delighted', 'confused', 'nervous'],
    'Atmospheric': ['thinking', 'mysterious'],
    'Digital': ['glitchy', 'robotic', 'sparkle'],
}

# Quick reference for parameter ranges (for UI sliders)
PARAMETER_RANGES = {
    'base_freq': (100, 1500, 500),       # min, max, default
    'contour_amount': (0.0, 1.0, 0.3),
    'vibrato_rate': (0, 15, 5),
    'vibrato_depth': (0.0, 0.1, 0.02),
    'formant_shift': (0.5, 2.0, 1.0),
    'breathiness': (0.0, 0.5, 0.1),
    'brightness': (0.0, 1.0, 0.7),
    'duration': (0.1, 1.0, 0.3),
    'attack': (0.005, 0.2, 0.02),
    'decay': (0.01, 0.3, 0.1),
    'sustain': (0.0, 1.0, 0.6),
    'release': (0.01, 0.3, 0.1),
    'tremolo_rate': (0, 20, 0),
    'tremolo_depth': (0.0, 0.5, 0.0),
}

CONTOUR_OPTIONS = ['flat', 'rising', 'falling', 'question', 'exclaim', 'wobble', 'nervous']

VOWEL_OPTIONS = ['a', 'e', 'i', 'o', 'u', 'ae', 'uh', 'er']